# In this notebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

## Introduction to Tensors

In [14]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [15]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [16]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [17]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [18]:
 # Check the dimension of our vector
 vector.ndim

1

In [19]:
# Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[10, 7],
                      [10, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [20]:
matrix.ndim

2

In [21]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [22]:
# What's the number of dimensions of another_matrix?
another_matrix.ndim

2

In [23]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], 
                      [[7, 8, 9], [10, 11, 12]], 
                      [[13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [24]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, an 1-dimensional tensor is a vector)


#### Creating tensors with `tf.Variable`

In [27]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [28]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [29]:
# How about we try .assign() ?
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [30]:
#  Let's try to change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [31]:
# Creating two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [32]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [33]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [34]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [35]:
first_random = tf.random.Generator.from_seed(56)
first_random = first_random.normal(shape=(3,3,2))
first_random

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[-0.67958915,  0.44723678],
        [-0.17811584,  0.24882518],
        [ 0.49689844,  0.8259971 ]],

       [[ 1.0340209 , -0.24918637],
        [-1.5780283 , -0.92161775],
        [ 0.268676  ,  0.9418312 ]],

       [[-0.9465717 , -0.7108357 ],
        [ 1.2995545 , -0.6149066 ],
        [-1.4713507 , -0.10086866]]], dtype=float32)>

In [36]:

tf.random.shuffle(first_random)

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[ 1.0340209 , -0.24918637],
        [-1.5780283 , -0.92161775],
        [ 0.268676  ,  0.9418312 ]],

       [[-0.9465717 , -0.7108357 ],
        [ 1.2995545 , -0.6149066 ],
        [-1.4713507 , -0.10086866]],

       [[-0.67958915,  0.44723678],
        [-0.17811584,  0.24882518],
        [ 0.49689844,  0.8259971 ]]], dtype=float32)>

In [37]:
second_random = tf.random.Generator.from_seed(56)
second_random = second_random.normal(shape=(3,3,3), dtype=tf.float16)
second_random

<tf.Tensor: shape=(3, 3, 3), dtype=float16, numpy=
array([[[-0.6797,  0.4473, -0.1781],
        [ 0.2488,  0.4968,  0.826 ],
        [ 1.034 , -0.2491, -1.578 ]],

       [[-0.9214,  0.2686,  0.942 ],
        [-0.947 , -0.711 ,  1.3   ],
        [-0.6147, -1.472 , -0.1009]],

       [[ 0.9604, -1.637 ,  0.1766],
        [-0.6704, -0.5034, -1.204 ],
        [-2.525 ,  0.0508,  1.722 ]]], dtype=float16)>

In [38]:

tf.random.shuffle(second_random, seed=42)

<tf.Tensor: shape=(3, 3, 3), dtype=float16, numpy=
array([[[-0.6797,  0.4473, -0.1781],
        [ 0.2488,  0.4968,  0.826 ],
        [ 1.034 , -0.2491, -1.578 ]],

       [[-0.9214,  0.2686,  0.942 ],
        [-0.947 , -0.711 ,  1.3   ],
        [-0.6147, -1.472 , -0.1009]],

       [[ 0.9604, -1.637 ,  0.1766],
        [-0.6704, -0.5034, -1.204 ],
        [-2.525 ,  0.0508,  1.722 ]]], dtype=float16)>

In [39]:

third_random = tf.random.Generator.from_seed(5)
counts = [10., 20.,399.]
# Probability of success.
probs = [0.2]
third_random = third_random.binomial(shape=[3], counts=counts, probs=probs)
third_random

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  4, 81], dtype=int32)>

In [40]:
tf.random.shuffle(third_random, seed=42)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([81,  2,  4], dtype=int32)>

In [41]:
fourth_random = tf.random.Generator.from_seed(45)
fourth_random = fourth_random.uniform(shape=(3,2,5))
fourth_random

<tf.Tensor: shape=(3, 2, 5), dtype=float32, numpy=
array([[[0.86540747, 0.8862978 , 0.27795732, 0.8857763 , 0.2179842 ],
        [0.29115117, 0.03953862, 0.8136791 , 0.8139852 , 0.52180684]],

       [[0.12496924, 0.5488483 , 0.7755773 , 0.6184403 , 0.24936223],
        [0.89341843, 0.28422844, 0.70332646, 0.2622137 , 0.4432162 ]],

       [[0.466465  , 0.05981874, 0.40098202, 0.69292355, 0.1284684 ],
        [0.22770369, 0.33691216, 0.5329138 , 0.5914326 , 0.21738243]]],
      dtype=float32)>

In [42]:
tf.random.shuffle(fourth_random,seed=1233)

<tf.Tensor: shape=(3, 2, 5), dtype=float32, numpy=
array([[[0.86540747, 0.8862978 , 0.27795732, 0.8857763 , 0.2179842 ],
        [0.29115117, 0.03953862, 0.8136791 , 0.8139852 , 0.52180684]],

       [[0.12496924, 0.5488483 , 0.7755773 , 0.6184403 , 0.24936223],
        [0.89341843, 0.28422844, 0.70332646, 0.2622137 , 0.4432162 ]],

       [[0.466465  , 0.05981874, 0.40098202, 0.69292355, 0.1284684 ],
        [0.22770369, 0.33691216, 0.5329138 , 0.5914326 , 0.21738243]]],
      dtype=float32)>

In [43]:
fifth_random = tf.random.Generator.from_seed(45)
fifth_random = fifth_random.uniform(shape=(3,2,4,5))
fifth_random

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0.86540747, 0.8862978 , 0.27795732, 0.8857763 , 0.2179842 ],
         [0.29115117, 0.03953862, 0.8136791 , 0.8139852 , 0.52180684],
         [0.12496924, 0.5488483 , 0.7755773 , 0.6184403 , 0.24936223],
         [0.89341843, 0.28422844, 0.70332646, 0.2622137 , 0.4432162 ]],

        [[0.466465  , 0.05981874, 0.40098202, 0.69292355, 0.1284684 ],
         [0.22770369, 0.33691216, 0.5329138 , 0.5914326 , 0.21738243],
         [0.5322075 , 0.05148339, 0.03951418, 0.41866875, 0.78939915],
         [0.04384279, 0.96955836, 0.49116182, 0.3706199 , 0.33535397]]],


       [[[0.02760839, 0.99757504, 0.52172756, 0.20307171, 0.7182547 ],
         [0.84263575, 0.9542595 , 0.90112185, 0.62839293, 0.08619452],
         [0.5679928 , 0.28763676, 0.18828917, 0.6658715 , 0.6190208 ],
         [0.04422736, 0.49626625, 0.6474861 , 0.3557682 , 0.32033885]],

        [[0.33705008, 0.7391062 , 0.16512096, 0.41555858, 0.78638244],
         [0.458

In [44]:
tf.random.shuffle(fifth_random)

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0.16467738, 0.54108894, 0.5765736 , 0.16844285, 0.8007604 ],
         [0.34483027, 0.30735934, 0.9700769 , 0.43336582, 0.51829636],
         [0.8555572 , 0.21962428, 0.76091194, 0.04762888, 0.5131633 ],
         [0.97339594, 0.33341944, 0.03152311, 0.28874612, 0.58736026]],

        [[0.75669694, 0.7060174 , 0.5588795 , 0.40088904, 0.8377521 ],
         [0.7651175 , 0.5402924 , 0.52445555, 0.8965409 , 0.4253844 ],
         [0.6824161 , 0.17499602, 0.4163201 , 0.8321508 , 0.313666  ],
         [0.15126252, 0.23609889, 0.56451845, 0.44649565, 0.41026497]]],


       [[[0.86540747, 0.8862978 , 0.27795732, 0.8857763 , 0.2179842 ],
         [0.29115117, 0.03953862, 0.8136791 , 0.8139852 , 0.52180684],
         [0.12496924, 0.5488483 , 0.7755773 , 0.6184403 , 0.24936223],
         [0.89341843, 0.28422844, 0.70332646, 0.2622137 , 0.4432162 ]],

        [[0.466465  , 0.05981874, 0.40098202, 0.69292355, 0.1284684 ],
         [0.227

In [45]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [46]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42)  # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:
> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

### Other ways to make tensors

In [47]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [48]:
# Create a tensor of all zeroes
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [49]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [50]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [51]:
C = tf.constant(numpy_A, shape=(3, 8))
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [52]:
D = tf.constant(numpy_A, shape=(2, 2, 2, 3))
D

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]], dtype=int32)>

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [53]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [54]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [59]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [60]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [61]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [63]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [64]:
some_list[:1]

[1]

In [66]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [69]:
rank_4_tensor[:, :1, :1, :]

<tf.Tensor: shape=(2, 1, 1, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [72]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [73]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [77]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [78]:
# Add an extra dimension to our rank 2 tensor without changing the information
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # equivalent to [:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [79]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [80]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [82]:
tf.expand_dims(rank_2_tensor, axis=1) # expand the 1-axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)