<a href="https://colab.research.google.com/github/ihsraham/TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

## Introduction to Tensors

In [144]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [145]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [146]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [147]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [148]:
 # Check the dimension of our vector
 vector.ndim

1

In [149]:
# Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[10, 7],
                      [10, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [150]:
matrix.ndim

2

In [151]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [152]:
# What's the number of dimensions of another_matrix?
another_matrix.ndim

2

In [153]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], 
                      [[7, 8, 9], [10, 11, 12]], 
                      [[13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [154]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, an 1-dimensional tensor is a vector)


#### Creating tensors with `tf.Variable`

In [155]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [157]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [158]:
# How about we try .assign() ?
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [160]:
#  Let's try to change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [161]:
# Creating two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [162]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [163]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [164]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [165]:
first_random = tf.random.Generator.from_seed(56)
first_random = first_random.normal(shape=(3,3,2))
first_random

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[-0.67958915,  0.44723678],
        [-0.17811584,  0.24882518],
        [ 0.49689844,  0.8259971 ]],

       [[ 1.0340209 , -0.24918637],
        [-1.5780283 , -0.92161775],
        [ 0.268676  ,  0.9418312 ]],

       [[-0.9465717 , -0.7108357 ],
        [ 1.2995545 , -0.6149066 ],
        [-1.4713507 , -0.10086866]]], dtype=float32)>

In [166]:

tf.random.shuffle(first_random)

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[ 1.0340209 , -0.24918637],
        [-1.5780283 , -0.92161775],
        [ 0.268676  ,  0.9418312 ]],

       [[-0.9465717 , -0.7108357 ],
        [ 1.2995545 , -0.6149066 ],
        [-1.4713507 , -0.10086866]],

       [[-0.67958915,  0.44723678],
        [-0.17811584,  0.24882518],
        [ 0.49689844,  0.8259971 ]]], dtype=float32)>

In [167]:
second_random = tf.random.Generator.from_seed(56)
second_random = second_random.normal(shape=(3,3,3), dtype=tf.float16)
second_random

<tf.Tensor: shape=(3, 3, 3), dtype=float16, numpy=
array([[[-0.6797,  0.4473, -0.1781],
        [ 0.2488,  0.4968,  0.826 ],
        [ 1.034 , -0.2491, -1.578 ]],

       [[-0.9214,  0.2686,  0.942 ],
        [-0.947 , -0.711 ,  1.3   ],
        [-0.6147, -1.472 , -0.1009]],

       [[ 0.9604, -1.637 ,  0.1766],
        [-0.6704, -0.5034, -1.204 ],
        [-2.525 ,  0.0508,  1.722 ]]], dtype=float16)>

In [168]:

tf.random.shuffle(second_random, seed=42)

<tf.Tensor: shape=(3, 3, 3), dtype=float16, numpy=
array([[[-0.6797,  0.4473, -0.1781],
        [ 0.2488,  0.4968,  0.826 ],
        [ 1.034 , -0.2491, -1.578 ]],

       [[-0.9214,  0.2686,  0.942 ],
        [-0.947 , -0.711 ,  1.3   ],
        [-0.6147, -1.472 , -0.1009]],

       [[ 0.9604, -1.637 ,  0.1766],
        [-0.6704, -0.5034, -1.204 ],
        [-2.525 ,  0.0508,  1.722 ]]], dtype=float16)>

In [169]:

third_random = tf.random.Generator.from_seed(5)
counts = [10., 20.,399.]
# Probability of success.
probs = [0.2]
third_random = third_random.binomial(shape=[3], counts=counts, probs=probs)
third_random

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  4, 81], dtype=int32)>

In [170]:
tf.random.shuffle(third_random, seed=42)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([81,  2,  4], dtype=int32)>

In [171]:
fourth_random = tf.random.Generator.from_seed(45)
fourth_random = fourth_random.uniform(shape=(3,2,5))
fourth_random

<tf.Tensor: shape=(3, 2, 5), dtype=float32, numpy=
array([[[0.86540747, 0.8862978 , 0.27795732, 0.8857763 , 0.2179842 ],
        [0.29115117, 0.03953862, 0.8136791 , 0.8139852 , 0.52180684]],

       [[0.12496924, 0.5488483 , 0.7755773 , 0.6184403 , 0.24936223],
        [0.89341843, 0.28422844, 0.70332646, 0.2622137 , 0.4432162 ]],

       [[0.466465  , 0.05981874, 0.40098202, 0.69292355, 0.1284684 ],
        [0.22770369, 0.33691216, 0.5329138 , 0.5914326 , 0.21738243]]],
      dtype=float32)>

In [172]:
tf.random.shuffle(fourth_random,seed=1233)

<tf.Tensor: shape=(3, 2, 5), dtype=float32, numpy=
array([[[0.86540747, 0.8862978 , 0.27795732, 0.8857763 , 0.2179842 ],
        [0.29115117, 0.03953862, 0.8136791 , 0.8139852 , 0.52180684]],

       [[0.12496924, 0.5488483 , 0.7755773 , 0.6184403 , 0.24936223],
        [0.89341843, 0.28422844, 0.70332646, 0.2622137 , 0.4432162 ]],

       [[0.466465  , 0.05981874, 0.40098202, 0.69292355, 0.1284684 ],
        [0.22770369, 0.33691216, 0.5329138 , 0.5914326 , 0.21738243]]],
      dtype=float32)>

In [173]:
fifth_random = tf.random.Generator.from_seed(45)
fifth_random = fifth_random.uniform(shape=(3,2,4,5))
fifth_random

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0.86540747, 0.8862978 , 0.27795732, 0.8857763 , 0.2179842 ],
         [0.29115117, 0.03953862, 0.8136791 , 0.8139852 , 0.52180684],
         [0.12496924, 0.5488483 , 0.7755773 , 0.6184403 , 0.24936223],
         [0.89341843, 0.28422844, 0.70332646, 0.2622137 , 0.4432162 ]],

        [[0.466465  , 0.05981874, 0.40098202, 0.69292355, 0.1284684 ],
         [0.22770369, 0.33691216, 0.5329138 , 0.5914326 , 0.21738243],
         [0.5322075 , 0.05148339, 0.03951418, 0.41866875, 0.78939915],
         [0.04384279, 0.96955836, 0.49116182, 0.3706199 , 0.33535397]]],


       [[[0.02760839, 0.99757504, 0.52172756, 0.20307171, 0.7182547 ],
         [0.84263575, 0.9542595 , 0.90112185, 0.62839293, 0.08619452],
         [0.5679928 , 0.28763676, 0.18828917, 0.6658715 , 0.6190208 ],
         [0.04422736, 0.49626625, 0.6474861 , 0.3557682 , 0.32033885]],

        [[0.33705008, 0.7391062 , 0.16512096, 0.41555858, 0.78638244],
         [0.458

In [174]:
tf.random.shuffle(fifth_random)

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0.16467738, 0.54108894, 0.5765736 , 0.16844285, 0.8007604 ],
         [0.34483027, 0.30735934, 0.9700769 , 0.43336582, 0.51829636],
         [0.8555572 , 0.21962428, 0.76091194, 0.04762888, 0.5131633 ],
         [0.97339594, 0.33341944, 0.03152311, 0.28874612, 0.58736026]],

        [[0.75669694, 0.7060174 , 0.5588795 , 0.40088904, 0.8377521 ],
         [0.7651175 , 0.5402924 , 0.52445555, 0.8965409 , 0.4253844 ],
         [0.6824161 , 0.17499602, 0.4163201 , 0.8321508 , 0.313666  ],
         [0.15126252, 0.23609889, 0.56451845, 0.44649565, 0.41026497]]],


       [[[0.86540747, 0.8862978 , 0.27795732, 0.8857763 , 0.2179842 ],
         [0.29115117, 0.03953862, 0.8136791 , 0.8139852 , 0.52180684],
         [0.12496924, 0.5488483 , 0.7755773 , 0.6184403 , 0.24936223],
         [0.89341843, 0.28422844, 0.70332646, 0.2622137 , 0.4432162 ]],

        [[0.466465  , 0.05981874, 0.40098202, 0.69292355, 0.1284684 ],
         [0.227

In [175]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [176]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42)  # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:
> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

### Other ways to make tensors

In [177]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [178]:
# Create a tensor of all zeroes
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [179]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [180]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [181]:
C = tf.constant(numpy_A, shape=(3, 8))
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [182]:
D = tf.constant(numpy_A, shape=(2, 2, 2, 3))
D

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]], dtype=int32)>

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [183]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [184]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [185]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [186]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [187]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [188]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [189]:
some_list[:1]

[1]

In [190]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [191]:
rank_4_tensor[:, :1, :1, :]

<tf.Tensor: shape=(2, 1, 1, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [192]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [193]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [194]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [195]:
# Add an extra dimension to our rank 2 tensor without changing the information
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # equivalent to [:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [196]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [197]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [198]:
tf.expand_dims(rank_2_tensor, axis=1) # expand the 1-axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**

`+`, `-`, `*`, `/`

In [199]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [200]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [201]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [202]:
# SUbtraction also works
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [203]:
# We can use the tensorflow built-in function too
# Use tensorflow.math to speed up operations
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [204]:
# Original is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules all tensors (or matrices) need to fulfil if we're going yo matrix multiply them:


1.   The inner dimensions must match
2.   The resulting matrix has the shape of the inner dimensions





In [205]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [206]:
# * does element wise multiplication
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [207]:
tensor1 = tf.constant([[1, 2, 5],
                      [7, 2, 1],
                      [3, 3, 3]])
tensor2 = tf.constant([[3, 5],
                      [6, 7],
                      [1, 8]])
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [208]:
# Matrix multiplication with Python operator "@"
tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [209]:
# Create a (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another (3, 2) tensor
Y = tf.constant([[7,8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [211]:
# Let's try to matmul tensors of same shape
tf.matmul(X, Y)

InvalidArgumentError: ignored

In [212]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [213]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [214]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [215]:
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [216]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [217]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

** The dot product **

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [218]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [219]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [220]:
# Perform matrix multiplicaation between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [221]:
# Perform matrix multiplication between X and  Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [222]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, shape=(2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [223]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors, and one of the axes does not line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

### Changing the datatype of a tensor

In [224]:
tf.__version__

'2.6.0'

In [225]:
# Create anew tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [226]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [227]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [228]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [229]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.



In [230]:
# Getting the absolute values
D = tf.constant([-7, 10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, 10], dtype=int32)>

In [231]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Het the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [232]:
# Creating a tensor
M = tf.constant([[27, 7],
                [19, 98]])
M

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27,  7],
       [19, 98]], dtype=int32)>

In [233]:
tf.reduce_min(M)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [234]:
tf.reduce_max(M)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [235]:
tf.reduce_mean(M)

<tf.Tensor: shape=(), dtype=int32, numpy=37>

In [236]:
tf.reduce_sum(M)

<tf.Tensor: shape=(), dtype=int32, numpy=151>

In [237]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([85, 56, 73, 76, 22, 70, 64,  7, 85, 29, 13, 31, 49, 50, 58, 85, 98,
       94, 89, 24, 42, 69, 32,  7, 37, 15,  7,  3, 18, 99, 23, 72,  9, 33,
       10, 63, 64, 55, 66, 51, 43, 30,  3, 79, 28, 71, 33, 59, 38, 96])>

In [238]:
tf.size(E), tf.shape(E), E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([50], dtype=int32)>,
 1)

In [239]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [240]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [241]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [242]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2413>

**Challenge:** With what we've just learned, find the variance and standard deviation of our `E` tensor using TensorFlow methods.

In [243]:
mean_E = tf.reduce_mean(E)
mean_E

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [244]:
var = E - mean_E
var

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 37,   8,  25,  28, -26,  22,  16, -41,  37, -19, -35, -17,   1,
         2,  10,  37,  50,  46,  41, -24,  -6,  21, -16, -41, -11, -33,
       -41, -45, -30,  51, -25,  24, -39, -15, -38,  15,  16,   7,  18,
         3,  -5, -18, -45,  31, -20,  23, -15,  11, -10,  48])>

In [245]:
var = var * var
var

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([1369,   64,  625,  784,  676,  484,  256, 1681, 1369,  361, 1225,
        289,    1,    4,  100, 1369, 2500, 2116, 1681,  576,   36,  441,
        256, 1681,  121, 1089, 1681, 2025,  900, 2601,  625,  576, 1521,
        225, 1444,  225,  256,   49,  324,    9,   25,  324, 2025,  961,
        400,  529,  225,  121,  100, 2304])>

In [246]:
variance = tf.reduce_sum(var).numpy()/np.shape(var)[0]
variance

812.58

In [247]:
stdev = np.sqrt(variance)
stdev

28.50578888576845

In [248]:
E_float = tf.cast(E, dtype=tf.float32)

In [249]:
tf.math.reduce_std(E_float)

<tf.Tensor: shape=(), dtype=float32, numpy=28.504604>

In [250]:
tf.math.reduce_variance(E_float)

<tf.Tensor: shape=(), dtype=float32, numpy=812.51245>

In [251]:
import tensorflow_probability as tfp

In [252]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=812>

In [253]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=812.5124000000001>

In [254]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=28.50460313703736>

### Find the positional maximum and minimum

In [255]:
# Create a new tesnor for finding the positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [256]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [257]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [258]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [259]:
# Check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [260]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [261]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [262]:
# Find the min value of F
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [263]:
# Check for equality
assert F[tf.argmin(F)] == tf.reduce_min(F)

### Squeezing a tensor (removing all single dimensions)

In [264]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [265]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [266]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors

In [267]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One-hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [268]:
# Specify custom values for one-hot encoding
tf.one_hot(some_list, depth=4, on_value="yo", off_value="no")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo', b'no', b'no', b'no'],
       [b'no', b'yo', b'no', b'no'],
       [b'no', b'no', b'yo', b'no'],
       [b'no', b'no', b'no', b'yo']], dtype=object)>

### Squaring, log, square root

In [269]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [270]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [271]:
# Find the square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [272]:
# Find the log 
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays.

**Note:** One of the main difference between a TensorFlow tensor and a NumPy array is that a tensor can be run on a GPU or TPU (for faster numerical processing).

In [273]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [274]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [275]:
# Convert tensor J to a NumPy array 
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [276]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [277]:
# Default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [35]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [36]:
!nvidia-smi

Sat Sep 18 22:25:11 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0    58W / 149W |    123MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> **Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.